#line 2 "/home/vcohen/bosilca-dplasma-1c0372a47a55/tools/q2j/q2j.l.c"

#line 4 "/home/vcohen/bosilca-dplasma-1c0372a47a55/tools/q2j/q2j.l.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5
#define YY_FLEX_SUBMINOR_VERSION 35
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;
#endif /* ! C99 */

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#endif /* ! FLEXINT_H */

#ifdef __cplusplus

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

/* C99 requires __STDC__ to be defined as 1. */
#if defined (__STDC__)

#define YY_USE_CONST

#endif	/* defined (__STDC__) */
#endif	/* ! __cplusplus */

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart(yyin  )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#define YY_BUF_SIZE 16384
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

    #define YY_LESS_LINENO(n)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */
    
	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = 0; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)

/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart (FILE *input_file  );
void yy_switch_to_buffer (YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer (FILE *file,int size  );
void yy_delete_buffer (YY_BUFFER_STATE b  );
void yy_flush_buffer (YY_BUFFER_STATE b  );
void yypush_buffer_state (YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state (void );

static void yyensure_buffer_stack (void );
static void yy_load_buffer_state (void );
static void yy_init_buffer (YY_BUFFER_STATE b,FILE *file  );

#define YY_FLUSH_BUFFER yy_flush_buffer(YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer (char *base,yy_size_t size  );
YY_BUFFER_STATE yy_scan_string (yyconst char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes (yyconst char *bytes,int len  );

void *yyalloc (yy_size_t  );
void *yyrealloc (void *,yy_size_t  );
void yyfree (void *  );

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer(yyin,YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

typedef unsigned char YY_CHAR;

FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;

typedef int yy_state_type;

extern int yylineno;

int yylineno = 1;

extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state (void );
static yy_state_type yy_try_NUL_trans (yy_state_type current_state  );
static int yy_get_next_buffer (void );
static void yy_fatal_error (yyconst char msg[]  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (size_t) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;

#define YY_NUM_RULES 119
#define YY_END_OF_BUFFER 120
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static yyconst flex_int16_t yy_accept[419] =
    {   0,
        0,    0,  120,  118,  117,  117,  105,  118,  111,  104,
      118,   99,  100,  109,  108,   96,  107,  103,  110,   64,
       64,   97,   93,  112,   98,  113,  116,   60,   60,   60,
       60,  101,  102,  114,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       94,  115,   95,  106,   92,    0,   70,    0,   78,   95,
       87,   79,    0,    0,    0,   76,   84,   74,   85,   75,
       86,    0,   68,    0,    1,    2,   77,   69,   63,    0,
        0,   64,    0,   64,  102,   94,  101,   83,   89,   91,
       90,   82,   60,   60,    0,    0,   60,   80,   60,   60,

       60,   60,   60,   60,   11,   60,   60,   60,   60,   60,
       60,   15,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   81,   88,   67,   66,   71,
        0,   68,    0,    0,   68,    0,   69,   63,   61,    0,
       65,   62,   73,   72,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   13,   60,   31,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,    0,   68,    0,
        0,    0,   68,    0,   69,   65,   62,   60,   60,   24,
       60,    8,   25,   60,   60,   60,   60,   12,   28,   60,

       60,   14,   60,   60,   60,   60,   60,   60,   32,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   52,   60,   60,    0,    0,    0,   68,
       60,   60,    7,   26,   60,   60,   60,   60,   30,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   46,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   50,   60,   60,   20,    0,    0,   60,   60,
       60,   60,   27,   29,   60,   60,   60,   33,   60,   60,
        6,   60,   16,   47,   17,   60,   48,   49,   18,   60,
       60,   60,   60,   60,   60,   60,   60,   60,    0,    0,

       60,   60,   60,   60,   60,   10,   34,   35,   36,   60,
       60,   60,   60,   19,   60,   60,   60,   37,   60,   60,
       60,   60,    0,    0,   60,   60,   60,   60,   60,   60,
       60,   60,    9,   43,   41,   45,   60,   38,   39,   40,
       60,   60,   51,   53,    0,    0,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   44,   42,   22,    0,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   23,   60,
       60,   60,   60,   58,   56,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   59,   60,   21,   60,

        3,   60,   60,   60,   57,   60,    5,   60,   60,   60,
       60,   60,   60,   54,   55,   60,    4,    0
    } ;

static yyconst flex_int32_t yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    3,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    5,    1,    1,    6,    7,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       20,   21,   22,   23,   22,   24,   22,   25,   26,   27,
       28,   29,   30,    1,   31,   32,   33,   34,   35,   36,
       37,   38,   39,   38,   40,   41,   42,   43,   44,   45,
       38,   46,   47,   48,   49,   50,   38,   51,   38,   38,
       52,   53,   54,   55,   56,    1,   57,   58,   59,   60,

       61,   62,   63,   64,   65,   38,   66,   67,   68,   69,
       70,   71,   72,   73,   74,   75,   76,   77,   78,   79,
       80,   81,   82,   83,   84,   85,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst flex_int32_t yy_meta[86] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    2,
        2,    2,    2,    2,    1,    1,    1,    1,    1,    1,
        2,    2,    2,    2,    2,    2,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    1,    1,    1,    3,    2,    2,    2,    2,
        2,    2,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    1,    1,    1,    1
    } ;

static yyconst flex_int16_t yy_base[423] =
    {   0,
        0,    0,  750,  751,  751,  751,  721,   81,   59,   82,
      134,  751,  751,  720,   78,  751,   79,  205,   81,  250,
      315,  718,  751,   88,  718,   67,  751,    0,  714,   93,
      703,  751,  751,  715,  666,  668,   47,   30,   45,   32,
      670,   56,  669,  665,  676,   55,  656,   57,  665,  670,
      751,  193,  751,  751,  751,  225,  751,  731,  751,  751,
      751,  751,  224,  226,  730,  751,  751,  751,  751,  751,
      751,  716,  375,   52,  751,  751,  751,  426,  479,  114,
      219,  208,    0,    0,  751,  751,  751,  702,  751,  751,
      751,  701,    0,  691,  230,  236,  696,  751,  651,  664,

      650,  666,  653,  659,  644,  645,  642,  642,  646,  642,
      639,    0,  638,  643,  654,  183,  640,   40,  188,  644,
      637,  638,  182,   62,  641,  751,  751,  751,  751,  751,
      301,  751,  629,  644,  219,  348,  751,  308,  233,  323,
      454,  310,  751,  751,  654,  655,  631,  643,  638,  625,
      178,  640,  638,  634,  626,  632,  635,    0,  621,  383,
      627,  626,  623,  611,  613,  616,  623,  215,  607,  607,
      620,  605,  609,  613,  617,  619,  608,  400,  489,  618,
      616,  515,  751,  408,  540,  751,  312,  637,  629,    0,
      604,    0,    0,  594,  603,  591,  599,    0,    0,  592,

      589,    0,  640,  643,  640,  604,  602,  583,    0,  589,
      582,  582,  579,  592,  582,  580,  585,  590,  589,  587,
      415,  577,  582,    0,  569,  582,  580,  585,  548,  565,
      575,  599,    0,    0,  560,  561,  565,  556,    0,  568,
      567,  566,  546,  541,  546,  561,  542,  547,    0,  555,
      552,  537,  553,  536,  546,  548,  585,  586,  583,  547,
      543,  524,    0,  529,  532,    0,  520,  533,  258,  538,
      517,  517,    0,    0,  516,  515,  505,    0,  523,  522,
        0,  516,    0,    0,    0,  519,    0,    0,    0,  512,
      517,  498,  497,  477,  471,  476,  487,  480,  476,  468,

      512,  499,  510,  408,  470,    0,    0,    0,    0,  451,
      449,  450,  463,    0,  444,  443,  442,    0,  459,  449,
      444,  431,  432,  420,  437,  434,  433,  409,  409,  397,
      404,  403,    0,    0,    0,    0,  393,    0,    0,    0,
      385,  384,    0,    0,  384,  398,  425,  424,  413,  384,
      366,  358,  343,  342,  353,    0,    0,  751,  338,  353,
      362,  349,  333,  343,  332,  314,  313,  326,  751,  352,
      344,  334,  313,    0,    0,  317,  313,  306,  319,  327,
      307,  293,  278,  279,  270,  287,  284,  285,  235,  237,
      251,  234,  263,  257,  258,  239,    0,  242,    0,  269,

        0,  252,  279,  275,    0,  264,    0,  238,  237,  239,
      191,  188,  213,    0,    0,  108,    0,  751,  632,  634,
      637,  103
    } ;

static yyconst flex_int16_t yy_def[423] =
    {   0,
      418,    1,  418,  418,  418,  418,  418,  419,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  420,  420,  420,
      420,  418,  418,  418,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      418,  418,  418,  418,  418,  419,  418,  419,  418,  418,
      418,  418,  421,  421,  421,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  422,   21,  418,  418,  418,  418,  418,  418,
      418,  418,  420,  420,  419,  421,  420,  418,  420,  420,

      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  418,  418,  418,  418,  418,
      418,  418,  418,  418,   78,  418,  418,  418,  418,  418,
      418,  422,  418,  418,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,

      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  418,  418,  418,  418,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  418,  418,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  418,  418,

      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  418,  418,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  418,  418,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  418,  418,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  418,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,

      420,  420,  420,  420,  420,  420,  420,  420,  420,  420,
      420,  420,  420,  420,  420,  420,  420,    0,  418,  418,
      418,  418
    } ;

static yyconst flex_int16_t yy_nxt[837] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   18,   19,   20,   21,   21,   21,
       21,   21,   21,   21,   22,   23,   24,   25,   26,   27,
       28,   28,   28,   29,   28,   28,   28,   28,   28,   28,
       30,   28,   28,   28,   31,   28,   28,   28,   28,   28,
       28,   32,    6,   33,   34,   28,   35,   36,   37,   38,
       39,   40,   41,   28,   42,   28,   43,   28,   28,   28,
       44,   28,   45,   46,   47,   48,   49,   50,   28,   28,
       28,   51,   52,   53,   54,   57,   59,   60,   61,   67,
      104,   75,   69,   86,   91,   92,   76,   95,  109,  105,

       96,  110,  166,  101,  142,   68,   70,   71,   77,   62,
      102,  106,   87,  107,   88,   89,  103,  112,  117,  118,
      167,  122,  133,  108,  113,  123,  175,  134,  176,  119,
      139,  139,  120,   58,   63,   63,   63,   63,   63,   63,
       63,  417,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   63,   63,   63,   63,   63,   63,
       63,   63,   63,   63,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   63,   65,   63,   63,   63,
       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,

       64,   64,   64,   64,   64,   64,   64,   64,   64,   64,
       64,   64,   64,   64,   64,   63,   63,   63,   63,   72,
      126,   73,   73,   73,   73,   73,   73,   73,   73,   57,
      140,  128,  140,  129,   57,  141,  141,  141,  141,  141,
      141,  141,  141,  418,  168,  163,  173,  416,   82,  139,
      139,  194,  195,  182,  183,  174,   82,  164,  403,  183,
      169,  404,  415,   74,   78,  414,   79,   79,   79,   79,
       79,   79,   79,   79,   82,  127,   65,   58,   65,  182,
      183,   80,   58,   82,   81,  183,  413,  216,   65,  217,
       82,  301,  412,  411,  410,  409,  302,  408,   82,  407,

       83,  406,  405,  402,  401,  303,  400,   80,  399,  398,
       81,  397,  178,  396,  178,  395,   82,  179,  179,  179,
      179,  179,  179,  179,  179,   82,  394,  393,   83,   78,
      392,   84,   84,   84,   84,   84,   84,   84,   84,  141,
      141,  141,  141,  141,  141,  141,  141,  391,  138,   81,
      187,  390,  187,  389,  388,   82,  138,  387,  187,  184,
      187,  184,  386,   82,  185,  185,  185,  185,  185,  185,
      185,  185,  385,  384,  138,   81,  187,  383,  187,  382,
      381,   82,  380,  138,  379,  187,  378,  187,  377,  376,
       82,   73,   73,   73,   73,   73,   73,   73,   73,  375,

      203,  374,  204,  373,  372,  205,  206,  371,  370,  131,
      132,  369,  368,  367,  366,  132,  179,  179,  179,  179,
      179,  179,  179,  179,  185,  185,  185,  185,  185,  185,
      185,  185,  257,  365,  258,  131,  132,  259,  260,  364,
      328,  132,  135,  135,  135,  135,  135,  135,  135,  135,
      207,  363,  362,  208,  361,  360,  359,  358,  357,  356,
      136,  137,  355,  354,  353,  352,  137,  329,  330,  351,
      141,  141,  141,  141,  141,  141,  141,  141,  350,  349,
      331,  332,  261,  348,  347,  262,  136,  137,  346,  186,
      345,  344,  137,   78,  186,   79,   79,   79,   79,   79,

       79,   79,   79,  343,  342,  179,  179,  179,  179,  179,
      179,  179,  179,   81,  341,  186,  340,  339,  338,  138,
      186,  337,  336,  335,  132,  334,  229,  138,  229,  132,
      333,  230,  230,  230,  230,  230,  230,  230,  230,   81,
      327,  326,  325,  324,  323,  138,  322,  321,  320,  319,
      132,  318,  317,  316,  138,  132,  185,  185,  185,  185,
      185,  185,  185,  185,  230,  230,  230,  230,  230,  230,
      230,  230,  315,  314,  313,  137,  312,  311,  310,  309,
      137,  230,  230,  230,  230,  230,  230,  230,  230,  308,
      307,  306,  305,  304,  300,  299,  298,  297,  296,  295,

      183,  137,  294,  293,  292,  183,  137,  291,  290,  289,
      288,  287,  286,  285,  284,  283,  282,  281,  280,  279,
      278,  277,  276,  275,  274,  273,  183,  272,  271,  270,
      269,  183,   56,   56,   56,   93,   93,   63,   63,   63,
      268,  267,  266,  265,  264,  263,  256,  255,  254,  253,
      252,  251,  250,  249,  248,  247,  246,  245,  244,  243,
      242,  241,  240,  239,  238,  237,  236,  235,  234,  233,
      232,  231,  228,  227,  226,  225,  224,  223,  222,  221,
      220,  219,  218,  215,  214,  213,  212,  211,  210,  209,
      202,  201,  200,  199,  198,  197,  196,  193,  192,  191,

      190,  189,  188,  181,  180,  177,  172,  171,  170,  165,
      162,  161,  160,  159,  158,  157,  156,  155,  154,  153,
      152,  151,  150,  149,  148,  147,  146,  145,  144,  143,
      130,  418,  418,  125,  124,  121,  116,  115,  114,  111,
      100,   99,   98,   97,   94,   90,   85,   66,   55,  418,
        3,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,

      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418
    } ;

static yyconst flex_int16_t yy_chk[837] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    8,    9,    9,   10,   15,
       38,   19,   17,   24,   26,   26,   19,   30,   40,   38,

       30,   40,  118,   37,  422,   15,   17,   17,   19,   10,
       37,   39,   24,   39,   24,   24,   37,   42,   46,   46,
      118,   48,   74,   39,   42,   48,  124,   74,  124,   46,
       80,   80,   46,    8,   11,   11,   11,   11,   11,   11,
       11,  416,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,

       11,   11,   11,   11,   11,   11,   11,   11,   11,   11,
       11,   11,   11,   11,   11,   11,   11,   11,   11,   18,
       52,   18,   18,   18,   18,   18,   18,   18,   18,   56,
       81,   63,   81,   64,   95,   81,   81,   81,   81,   81,
       81,   81,   81,   96,  119,  116,  123,  413,   82,  139,
      139,  151,  151,  135,  135,  123,   82,  116,  396,  135,
      119,  396,  412,   18,   20,  411,   20,   20,   20,   20,
       20,   20,   20,   20,   82,   52,   63,   56,   64,  135,
      135,   20,   95,   82,   20,  135,  410,  168,   96,  168,
       20,  269,  409,  408,  406,  404,  269,  403,   20,  402,

       20,  400,  398,  395,  394,  269,  393,   20,  392,  391,
       20,  390,  131,  389,  131,  388,   20,  131,  131,  131,
      131,  131,  131,  131,  131,   20,  387,  386,   20,   21,
      385,   21,   21,   21,   21,   21,   21,   21,   21,  140,
      140,  140,  140,  140,  140,  140,  140,  384,  138,   21,
      142,  383,  187,  382,  381,   21,  138,  380,  142,  136,
      187,  136,  379,   21,  136,  136,  136,  136,  136,  136,
      136,  136,  378,  377,  138,   21,  142,  376,  187,  373,
      372,   21,  371,  138,  370,  142,  368,  187,  367,  366,
       21,   73,   73,   73,   73,   73,   73,   73,   73,  365,

      160,  364,  160,  363,  362,  160,  160,  361,  360,   73,
       73,  359,  355,  354,  353,   73,  178,  178,  178,  178,
      178,  178,  178,  178,  184,  184,  184,  184,  184,  184,
      184,  184,  221,  352,  221,   73,   73,  221,  221,  351,
      304,   73,   78,   78,   78,   78,   78,   78,   78,   78,
      160,  350,  349,  160,  348,  347,  346,  345,  342,  341,
       78,   78,  337,  332,  331,  330,   78,  304,  304,  329,
      141,  141,  141,  141,  141,  141,  141,  141,  328,  327,
      304,  304,  221,  326,  325,  221,   78,   78,  324,  141,
      323,  322,   78,   79,  141,   79,   79,   79,   79,   79,

       79,   79,   79,  321,  320,  179,  179,  179,  179,  179,
      179,  179,  179,   79,  319,  141,  317,  316,  315,   79,
      141,  313,  312,  311,  179,  310,  182,   79,  182,  179,
      305,  182,  182,  182,  182,  182,  182,  182,  182,   79,
      303,  302,  301,  300,  299,   79,  298,  297,  296,  295,
      179,  294,  293,  292,   79,  179,  185,  185,  185,  185,
      185,  185,  185,  185,  229,  229,  229,  229,  229,  229,
      229,  229,  291,  290,  286,  185,  282,  280,  279,  277,
      185,  230,  230,  230,  230,  230,  230,  230,  230,  276,
      275,  272,  271,  270,  268,  267,  265,  264,  262,  261,

      230,  185,  260,  259,  258,  230,  185,  257,  256,  255,
      254,  253,  252,  251,  250,  248,  247,  246,  245,  244,
      243,  242,  241,  240,  238,  237,  230,  236,  235,  232,
      231,  230,  419,  419,  419,  420,  420,  421,  421,  421,
      228,  227,  226,  225,  223,  222,  220,  219,  218,  217,
      216,  215,  214,  213,  212,  211,  210,  208,  207,  206,
      205,  204,  203,  201,  200,  197,  196,  195,  194,  191,
      189,  188,  181,  180,  177,  176,  175,  174,  173,  172,
      171,  170,  169,  167,  166,  165,  164,  163,  162,  161,
      159,  157,  156,  155,  154,  153,  152,  150,  149,  148,

      147,  146,  145,  134,  133,  125,  122,  121,  120,  117,
      115,  114,  113,  111,  110,  109,  108,  107,  106,  105,
      104,  103,  102,  101,  100,   99,   97,   94,   92,   88,
       72,   65,   58,   50,   49,   47,   45,   44,   43,   41,
       36,   35,   34,   31,   29,   25,   22,   14,    7,    3,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,

      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418,  418,  418,  418,  418,
      418,  418,  418,  418,  418,  418
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "src/q2j.l"
#line 9 "src/q2j.l"
/*
 * Copyright (c) 2009-2010 The University of Tennessee and The University
 *                         of Tennessee Research Foundation.  All rights
 *                         reserved.
 */

#include "parsec/parsec_config.h"
#include <stdio.h>
#include <stdlib.h>
#include "node_struct.h"
#include "parse_utility.h"
#include "symtab.h"
#include "starpu_struct.h"
#include "q2j.y.h"


int check_type();
void count();
void comment();
void cpp_comment();

#line 799 "/home/vcohen/bosilca-dplasma-1c0372a47a55/tools/q2j/q2j.l.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals (void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy (void );

int yyget_debug (void );

void yyset_debug (int debug_flag  );

YY_EXTRA_TYPE yyget_extra (void );

void yyset_extra (YY_EXTRA_TYPE user_defined  );

FILE *yyget_in (void );

void yyset_in  (FILE * in_str  );

FILE *yyget_out (void );

void yyset_out  (FILE * out_str  );

int yyget_leng (void );

char *yyget_text (void );

int yyget_lineno (void );

void yyset_lineno (int line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap (void );
#else
extern int yywrap (void );
#endif
#endif

    static void yyunput (int c,char *buf_ptr  );
    
#ifndef yytext_ptr
static void yy_flex_strncpy (char *,yyconst char *,int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * );
#endif

#ifndef YY_NO_INPUT

#ifdef __cplusplus
static int yyinput (void );
#else
static int input (void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = fread(buf, 1, max_size, yyin))==0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;
    
#line 32 "src/q2j.l"

#line 983 "/home/vcohen/bosilca-dplasma-1c0372a47a55/tools/q2j/q2j.l.c"

	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer(yyin,YY_BUF_SIZE );
		}

		yy_load_buffer_state( );
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 419 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 751 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 33 "src/q2j.l"
{ comment(); }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 34 "src/q2j.l"
{ cpp_comment(); }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 36 "src/q2j.l"
{ count(); return(DIR_PARSEC_INVARIANT); }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 37 "src/q2j.l"
{ count(); return(DIR_PARSEC_DATA_COLOCATED); }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 38 "src/q2j.l"
{ count(); return(DIR_PARSEC_TASK_START); }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 39 "src/q2j.l"
{ count(); return(PRAGMA); }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 40 "src/q2j.l"
{ count(); return(BREAK); }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 41 "src/q2j.l"
{ count(); return(CASE); }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 42 "src/q2j.l"
{ count(); return(CONTINUE); }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 43 "src/q2j.l"
{ count(); return(DEFAULT); }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 44 "src/q2j.l"
{ count(); return(DO); }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 45 "src/q2j.l"
{ count(); return(ELSE); }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 46 "src/q2j.l"
{ count(); return(FOR); }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 47 "src/q2j.l"
{ count(); return(GOTO); }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 48 "src/q2j.l"
{ count(); return(IF); }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 49 "src/q2j.l"
{ count(); return(RETURN); }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 50 "src/q2j.l"
{ count(); return(SIZEOF); }
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 51 "src/q2j.l"
{ count(); return(SWITCH); }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 52 "src/q2j.l"
{ count(); return(TYPEDEF); }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 53 "src/q2j.l"
{ count(); return(WHILE); }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 55 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(STARPU_CODELET);
                        }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 60 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return (STARPU_FUNC);
                        }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 65 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return (STARPU_FUNC);
                        }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 71 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(AUTO);
                        }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 76 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(CHAR);
                        }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 81 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(CONST);
                        }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 86 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(DOUBLE);
                        }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 91 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(ENUM);
                        }
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 96 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(EXTERN);
                        }
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 101 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(FLOAT);
                        }
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 106 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(INT);
                        }
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 111 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(LONG);
                        }
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 116 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(INT8);
                        }
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 121 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(INT16);
                        }
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 126 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(INT32);
                        }
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 131 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(INT64);
                        }
	YY_BREAK
case 37:
YY_RULE_SETUP
#line 136 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(UINT8);
                        }
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 141 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(UINT16);
                        }
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 146 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(UINT32);
                        }
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 151 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(UINT64);
                        }
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 156 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(INTPTR);
                        }
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 161 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(UINTPTR);
                        }
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 166 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(INTMAX);
                        }
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 171 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(UINTMAX);
                        }
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 177 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(REGISTER);
                        }
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 182 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(SHORT);
                        }
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 187 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(SIGNED);
                        }
	YY_BREAK
case 48:
YY_RULE_SETUP
#line 192 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(STATIC);
                        }
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 197 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(STRUCT);
                        }
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 202 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(UNION);
                        }
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 207 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(UNSIGNED);
                        }
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 212 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(VOID);
                        }
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 217 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(VOLATILE);
                        }
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 222 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(PLASMA_COMPLEX32_T);
			}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 227 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(PLASMA_COMPLEX64_T);
			}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 232 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(PLASMA_ENUM);
			}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 237 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(PLASMA_SEQUENCE);
			}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 242 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(PLASMA_DESC);
			}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 247 "src/q2j.l"
{ count();
                          yylval.string = strdup(yytext);
                          return(PLASMA_REQUEST);
			}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 252 "src/q2j.l"
{ count(); 
                          if( IDENTIFIER == check_type()){
                              memset(&(yylval.node),0,sizeof(node_t));
                              yylval.node.u.var_name = strdup(yytext);
                              yylval.node.type = IDENTIFIER;
                              yylval.node.u.kids.kid_count = 0;
                              yylval.node.symtab = st_get_current_st();
                              yylval.node.lineno = yyget_lineno();
                              return(IDENTIFIER);
                          }else{
                              yylval.string = strdup(yytext);
                              return(TYPE_NAME);
                          }
                        }
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 267 "src/q2j.l"
{ 
                          int i,len;
                          char *num = yytext+2;
                          count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.const_val.i64_value = 0;
                          len = strlen(num)-1;
                          for(i=len; i>=0; i--){
                              yylval.node.const_val.i64_value += ((*(num+i))-'0')<<(len-i);
                          }
                          yylval.node.type = BIN_MASK;
                          yylval.node.u.kids.kid_count = 0;
                          yylval.node.lineno = yyget_lineno();
                          return(BIN_MASK);
                        }
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 283 "src/q2j.l"
{ count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.const_val.i64_value = strtoll(yytext, NULL, 16);
                          yylval.node.type = INTCONSTANT;
                          yylval.node.u.kids.kid_count = 0;
                          yylval.node.lineno = yyget_lineno();
                          return(INTCONSTANT);
                        }
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 292 "src/q2j.l"
{ count();
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.const_val.i64_value = strtoll(yytext, NULL, 8);
                          yylval.node.type = INTCONSTANT;
                          yylval.node.u.kids.kid_count = 0;
                          yylval.node.lineno = yyget_lineno();
                          return(INTCONSTANT);
                        }
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 300 "src/q2j.l"
{ count();
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.const_val.i64_value = atoll(yytext);
                          yylval.node.type = INTCONSTANT;
                          yylval.node.u.kids.kid_count = 0;
                          yylval.node.lineno = yyget_lineno();
                          return(INTCONSTANT);
                        }
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 308 "src/q2j.l"
{ count();
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.const_val.i64_value = atoll(yytext);
                          yylval.node.type = INTCONSTANT;
                          yylval.node.u.kids.kid_count = 0;
                          yylval.node.lineno = yyget_lineno();
                          return(INTCONSTANT);
                        }
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 317 "src/q2j.l"
{ count();
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.const_val.str = strdup(yytext);
                          yylval.node.type = STRING_LITERAL;
                          yylval.node.u.kids.kid_count = 0;
                          yylval.node.lineno = yyget_lineno(); 
                          return(STRING_LITERAL); 
}
	YY_BREAK
case 67:
/* rule 67 can match eol */
YY_RULE_SETUP
#line 326 "src/q2j.l"
{ count();
                          fprintf(stdout, "heheheh %s\n", yytext);
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.const_val.f64_value = atof(yytext);
                          yylval.node.type = FLOATCONSTANT;
                          yylval.node.u.kids.kid_count = 0;
                          yylval.node.lineno = yyget_lineno();
                          return(FLOATCONSTANT);
                        }
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 336 "src/q2j.l"
{ count();
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.const_val.f64_value = atof(yytext);
                          yylval.node.type = FLOATCONSTANT;
                          yylval.node.u.kids.kid_count = 0;
                          yylval.node.lineno = yyget_lineno();
                          return(FLOATCONSTANT);
                        }
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 344 "src/q2j.l"
{ count();
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.const_val.f64_value = atof(yytext);
                          yylval.node.type = FLOATCONSTANT;
                          yylval.node.u.kids.kid_count = 0;
                          yylval.node.lineno = yyget_lineno();
                          return(FLOATCONSTANT);
                        }
	YY_BREAK
case 70:
/* rule 70 can match eol */
YY_RULE_SETUP
#line 353 "src/q2j.l"
{ count();
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.const_val.str = strdup(yytext);
                          yylval.node.type = STRING_LITERAL;
                          yylval.node.u.kids.kid_count = 0;
                          yylval.node.lineno = yyget_lineno();
                          return(STRING_LITERAL);
                        }
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 362 "src/q2j.l"
{ count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.type = ELLIPSIS;
                          yylval.node.lineno = yyget_lineno();
                          return(ELLIPSIS);
                        }
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 369 "src/q2j.l"
{ count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.type = RIGHT_ASSIGN;
                          yylval.node.lineno = yyget_lineno();
                          return(RIGHT_ASSIGN);
                        }
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 376 "src/q2j.l"
{ count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.type = LEFT_ASSIGN;
                          yylval.node.lineno = yyget_lineno();
                          return(LEFT_ASSIGN);
                        }
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 383 "src/q2j.l"
{ count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.type = ADD_ASSIGN;
                          yylval.node.lineno = yyget_lineno();
                          return(ADD_ASSIGN);
                        }
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 390 "src/q2j.l"
{ count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.type = SUB_ASSIGN;
                          yylval.node.lineno = yyget_lineno();
                          return(SUB_ASSIGN);
                        }
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 397 "src/q2j.l"
{ count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.type = MUL_ASSIGN;
                          yylval.node.lineno = yyget_lineno();
                          return(MUL_ASSIGN);
                        }
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 404 "src/q2j.l"
{ count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.type = DIV_ASSIGN;
                          yylval.node.lineno = yyget_lineno();
                          return(DIV_ASSIGN);
                        }
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 411 "src/q2j.l"
{ count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.type = MOD_ASSIGN;
                          yylval.node.lineno = yyget_lineno();
                          return(MOD_ASSIGN);
                        }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 418 "src/q2j.l"
{ count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.type = AND_ASSIGN;
                          yylval.node.lineno = yyget_lineno();
                          return(AND_ASSIGN);
                        }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 425 "src/q2j.l"
{ count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.type = XOR_ASSIGN;
                          yylval.node.lineno = yyget_lineno();
                          return(XOR_ASSIGN);
                        }
	YY_BREAK
case 81:
YY_RULE_SETUP
#line 432 "src/q2j.l"
{ count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.type = OR_ASSIGN;
                          yylval.node.lineno = yyget_lineno();
                          return(OR_ASSIGN);
                        }
	YY_BREAK
case 82:
YY_RULE_SETUP
#line 439 "src/q2j.l"
{ count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.type = RIGHT_OP;
                          yylval.node.lineno = yyget_lineno();
                          return(RIGHT_OP);
                        }
	YY_BREAK
case 83:
YY_RULE_SETUP
#line 446 "src/q2j.l"
{ count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.type = LEFT_OP;
                          yylval.node.lineno = yyget_lineno();
                          return(LEFT_OP);
                        }
	YY_BREAK
case 84:
YY_RULE_SETUP
#line 453 "src/q2j.l"
{ count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.type = INC_OP;
                          yylval.node.lineno = yyget_lineno();
                          return(INC_OP);
                        }
	YY_BREAK
case 85:
YY_RULE_SETUP
#line 460 "src/q2j.l"
{ count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.type = DEC_OP;
                          yylval.node.lineno = yyget_lineno();
                          return(DEC_OP);
                        }
	YY_BREAK
case 86:
YY_RULE_SETUP
#line 467 "src/q2j.l"
{ count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.type = PTR_OP;
                          yylval.node.lineno = yyget_lineno();
                          return(PTR_OP);
                        }
	YY_BREAK
case 87:
YY_RULE_SETUP
#line 474 "src/q2j.l"
{ count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.type = L_AND;
                          yylval.node.lineno = yyget_lineno();
                          return(L_AND);
                        }
	YY_BREAK
case 88:
YY_RULE_SETUP
#line 481 "src/q2j.l"
{ count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.type = L_OR;
                          yylval.node.lineno = yyget_lineno();
                          return(L_OR);
                        }
	YY_BREAK
case 89:
YY_RULE_SETUP
#line 488 "src/q2j.l"
{ count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.type = LE_OP;
                          yylval.node.lineno = yyget_lineno();
                          return(LE_OP);
                        }
	YY_BREAK
case 90:
YY_RULE_SETUP
#line 495 "src/q2j.l"
{ count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.type = GE_OP;
                          yylval.node.lineno = yyget_lineno();
                          return(GE_OP);
                        }
	YY_BREAK
case 91:
YY_RULE_SETUP
#line 502 "src/q2j.l"
{ count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.type = EQ_OP;
                          yylval.node.lineno = yyget_lineno();
                          return(EQ_OP);
                        }
	YY_BREAK
case 92:
YY_RULE_SETUP
#line 509 "src/q2j.l"
{ count(); 
                          memset(&(yylval.node),0,sizeof(node_t));
                          yylval.node.type = NE_OP;
                          yylval.node.lineno = yyget_lineno();
                          return(NE_OP);
                        }
	YY_BREAK
case 93:
YY_RULE_SETUP
#line 517 "src/q2j.l"
{ count(); return(';'); }
	YY_BREAK
case 94:
YY_RULE_SETUP
#line 518 "src/q2j.l"
{ count();
                          (void)st_enter_new_scope();
                          return('{');
                        }
	YY_BREAK
case 95:
YY_RULE_SETUP
#line 522 "src/q2j.l"
{ count();
                          (void)st_exit_scope();
                          return('}');
                        }
	YY_BREAK
case 96:
YY_RULE_SETUP
#line 526 "src/q2j.l"
{ count(); return(','); }
	YY_BREAK
case 97:
YY_RULE_SETUP
#line 527 "src/q2j.l"
{ count(); return(':'); }
	YY_BREAK
case 98:
YY_RULE_SETUP
#line 528 "src/q2j.l"
{ count(); return('='); }
	YY_BREAK
case 99:
YY_RULE_SETUP
#line 529 "src/q2j.l"
{ count(); return('('); }
	YY_BREAK
case 100:
YY_RULE_SETUP
#line 530 "src/q2j.l"
{ count(); return(')'); }
	YY_BREAK
case 101:
YY_RULE_SETUP
#line 531 "src/q2j.l"
{ count(); return('['); }
	YY_BREAK
case 102:
YY_RULE_SETUP
#line 532 "src/q2j.l"
{ count(); return(']'); }
	YY_BREAK
case 103:
YY_RULE_SETUP
#line 533 "src/q2j.l"
{ count(); return('.'); }
	YY_BREAK
case 104:
YY_RULE_SETUP
#line 534 "src/q2j.l"
{ count(); return('&'); }
	YY_BREAK
case 105:
YY_RULE_SETUP
#line 535 "src/q2j.l"
{ count(); return('!'); }
	YY_BREAK
case 106:
YY_RULE_SETUP
#line 536 "src/q2j.l"
{ count(); return('~'); }
	YY_BREAK
case 107:
YY_RULE_SETUP
#line 537 "src/q2j.l"
{ count(); return('-'); }
	YY_BREAK
case 108:
YY_RULE_SETUP
#line 538 "src/q2j.l"
{ count(); return('+'); }
	YY_BREAK
case 109:
YY_RULE_SETUP
#line 539 "src/q2j.l"
{ count(); return('*'); }
	YY_BREAK
case 110:
YY_RULE_SETUP
#line 540 "src/q2j.l"
{ count(); return('/'); }
	YY_BREAK
case 111:
YY_RULE_SETUP
#line 541 "src/q2j.l"
{ count(); return('%'); }
	YY_BREAK
case 112:
YY_RULE_SETUP
#line 542 "src/q2j.l"
{ count(); return('<'); }
	YY_BREAK
case 113:
YY_RULE_SETUP
#line 543 "src/q2j.l"
{ count(); return('>'); }
	YY_BREAK
case 114:
YY_RULE_SETUP
#line 544 "src/q2j.l"
{ count(); return('^'); }
	YY_BREAK
case 115:
YY_RULE_SETUP
#line 545 "src/q2j.l"
{ count(); return('|'); }
	YY_BREAK
case 116:
YY_RULE_SETUP
#line 546 "src/q2j.l"
{ count(); return('?'); }
	YY_BREAK
case 117:
/* rule 117 can match eol */
YY_RULE_SETUP
#line 548 "src/q2j.l"
{ count(); }
	YY_BREAK
case 118:
YY_RULE_SETUP
#line 549 "src/q2j.l"
{ /* ignore bad characters */ }
	YY_BREAK
case 119:
YY_RULE_SETUP
#line 551 "src/q2j.l"
ECHO;
	YY_BREAK
#line 1988 "/home/vcohen/bosilca-dplasma-1c0372a47a55/tools/q2j/q2j.l.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap( ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	register char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	register char *source = (yytext_ptr);
	register int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr)) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc((void *) b->yy_ch_buf,b->yy_buf_size + 2  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), (size_t) num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart(yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if ((yy_size_t) ((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		yy_size_t new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc((void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf,new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	register yy_state_type yy_current_state;
	register char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 419 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	register int yy_is_jam;
    	register char *yy_cp = (yy_c_buf_p);

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 419 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 418);

	return yy_is_jam ? 0 : yy_current_state;
}

    static void yyunput (int c, register char * yy_bp )
{
	register char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = (yy_n_chars) + 2;
		register char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		register char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (yy_c_buf_p) - (yytext_ptr);
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart(yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap( ) )
						return EOF;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer(yyin,YY_BUF_SIZE );
	}

	yy_init_buffer(YY_CURRENT_BUFFER,input_file );
	yy_load_buffer_state( );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state( );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc(b->yy_buf_size + 2  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer(b,file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree((void *) b->yy_ch_buf  );

	yyfree((void *) b  );
}

#ifndef __cplusplus
extern int isatty (int );
#endif /* __cplusplus */
    
/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer(b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state( );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state( );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state( );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	int num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
		num_to_alloc = 1;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );
								  
		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));
				
		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		int grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object. 
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yyalloc(sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer(b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (yyconst char * yystr )
{
    
	return yy_scan_bytes(yystr,strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param bytes the byte buffer to scan
 * @param len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (yyconst char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = _yybytes_len + 2;
	buf = (char *) yyalloc(n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer(buf,n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yy_fatal_error (yyconst char* msg )
{
    	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
        
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param line_number
 * 
 */
void yyset_lineno (int  line_number )
{
    
    yylineno = line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  in_str )
{
        yyin = in_str ;
}

void yyset_out (FILE *  out_str )
{
        yyout = out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  bdebug )
{
        yy_flex_debug = bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = 0;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = (char *) 0;
    (yy_init) = 0;
    (yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = (FILE *) 0;
    yyout = (FILE *) 0;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer(YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, yyconst char * s2, int n )
{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (yyconst char * s )
{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
	return (void *) malloc( size );
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
}

void yyfree (void * ptr )
{
	free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 551 "src/q2j.l"



int yywrap(){
	return(1);
}


void cpp_comment(){
    int c;
#ifdef __cplusplus
    while ((c = yyinput()) != '\n' && c != 0);
#else
    while ((c = input()) != '\n' && c != 0);
#endif
    if( c == '\n' )
        yyset_lineno(yyget_lineno() + 1 );
}

void comment(){
	int c, c1;

loop:
#ifdef __cplusplus
	while ((c = yyinput()) != '*' && c != 0){
#else
	while ((c = input()) != '*' && c != 0){
#endif
            if( c == '\n' )
                yyset_lineno(yyget_lineno() + 1 );
        }

#ifdef __cplusplus
	if ((c1 = yyinput()) != '/' && c != 0)
#else
	if ((c1 = input()) != '/' && c != 0)
#endif
	{
		unput(c1);
		goto loop;
	}

//	if (c != 0)
//		putchar(c1);
}


int column = 0;

void count()
{
	int i;

	for (i = 0; yytext[i] != '\0'; i++)
		if (yytext[i] == '\n'){
			column = 0;
			yyset_lineno(yyget_lineno() + 1 );
                }
		else if (yytext[i] == '\t')
			column += 8 - (column % 8);
		else
			column++;

	/*ECHO;*/
}


int check_type() {

    if( NULL != lookup_type(yytext) ){
        return(TYPE_NAME);
    }

    return(IDENTIFIER);
}

