export OMEGA_BASE=/Users/adanalis/Desktop/Research/PLASMA_Distributed/Related_Stuff/Omega
export YACC=yacc -d -y --verbose
export LEX=flex
export CC=g++-4.2
export CCFLAGS=-g -Wall
export LINKER=g++

all:
	$(MAKE) -C src
#	$(MAKE) -C src clean

clean:
	$(MAKE) -C src clean
