export OMEGA_BASE=/home/adanalis/pub/Omega
export YACC=yacc -d -y --verbose
export LEX=flex
export CC=g++
export CCFLAGS=-g -Wall
export LINKER=g++

all:
	$(MAKE) -C src
	$(MAKE) -C src clean

clean:
	$(MAKE) -C src clean
