if(TARGET atomics)
  add_test(parsec/class/atomics ${SHM_TEST_CMD_LIST} class/atomics -c 4)
endif()
add_test(parsec/class/rwlock ${SHM_TEST_CMD_LIST} class/rwlock -c 4)
add_test(parsec/class/lifo ${SHM_TEST_CMD_LIST} class/lifo -c 4)
add_test(parsec/class/list ${SHM_TEST_CMD_LIST} class/list -c 4)
add_test(parsec/class/hash ${SHM_TEST_CMD_LIST} class/hash -\# 65536 -r 4 -n)
add_test(parsec/class/future ${SHM_TEST_CMD_LIST} class/future -c 4)
add_test(parsec/class/future_datacopy ${SHM_TEST_CMD_LIST} class/future_datacopy)

if(TARGET atomics_inline)
  add_test(parsec/class/atomics:inline ${SHM_TEST_CMD_LIST} class/atomics_inline -c 4)
endif()
add_test(parsec/class/rwlock:inline ${SHM_TEST_CMD_LIST} class/rwlock_inline -c 4)
add_test(parsec/class/lifo:inline ${SHM_TEST_CMD_LIST} class/lifo_inline -c 4)
add_test(parsec/class/list:inline ${SHM_TEST_CMD_LIST} class/list_inline -c 4)
add_test(parsec/class/hash:inline ${SHM_TEST_CMD_LIST} class/hash_inline -\# 65536 -r 4 -n)
