if(TARGET atomics)
  add_test(class/atomics ${SHM_TEST_CMD_LIST} ./atomics)
endif()
add_test(class/rwlock ${SHM_TEST_CMD_LIST} ./rwlock)
add_test(class/lifo ${SHM_TEST_CMD_LIST} ./lifo)
add_test(class/list ${SHM_TEST_CMD_LIST} ./list)
add_test(class/hash ${SHM_TEST_CMD_LIST} ./hash)
add_test(class/future ${SHM_TEST_CMD_LIST} ./future)
add_test(class/future/datacopy ${SHM_TEST_CMD_LIST} ./future_datacopy)

if(TARGET atomics_inline)
  add_test(class/inline/atomics ${SHM_TEST_CMD_LIST} ./atomics_inline)
endif()
add_test(class/inline/rwlock ${SHM_TEST_CMD_LIST} ./rwlock_inline)
add_test(class/inline/lifo ${SHM_TEST_CMD_LIST} ./lifo_inline)
add_test(class/inline/list ${SHM_TEST_CMD_LIST} ./list_inline)
add_test(class/inline/hash ${SHM_TEST_CMD_LIST} ./hash_inline)
