find_package(PkgConfig QUIET)

if(PKG_CONFIG_FOUND)
    pkg_check_modules(LEVEL_ZERO level-zero)
    if(LEVEL_ZERO_FOUND)
        pkg_get_variable(LEVEL_ZERO_LIBRARY_DIR level-zero libdir)
        pkg_get_variable(LEVEL_ZERO_INCLUDE_DIR level-zero includedir)
        add_library(level_zero::ze_loader UNKNOWN IMPORTED GLOBAL)
        set_property(TARGET level_zero::ze_loader PROPERTY IMPORTED_LOCATION "${LEVEL_ZERO_LIBRARY_DIR}/libze_loader.so")
        set_property(TARGET level_zero::ze_loader PROPERTY INTERFACE "${LEVEL_ZERO_INCLUDE_DIR}/level-zero/ze_api.h")
        include_directories("${LEVEL_ZERO_INCLUDE_DIR}/level-zero/")
    endif(LEVEL_ZERO_FOUND)
else(PKG_CONFIG_FOUND)

endif(PKG_CONFIG_FOUND)