static const char *tooltip_script = 
    "      var SVGDocument = null;\n"
    "      var SVGRoot = null;\n"
    "      var SVGViewBox = null;\n"
    "      var svgns = 'http://www.w3.org/2000/svg';\n"
    "      var xlinkns = 'http://www.w3.org/1999/xlink';\n"
    "      var toolTip = null;\n"
    "      var TrueCoords = null;\n"
    "      var tipBox = null;\n"
    "      var tipText = null;\n"
    "      var tipTitle = null;\n"
    "      var tipDesc = null;\n"
    "\n"
    "      var lastElement = null;\n"
    "      var titleText = '';\n"
    "      var titleDesc = '';\n"
    "\n"
    "\n"
    "      function Init(evt)\n"
    "      {\n"
    "         SVGDocument = evt.target.ownerDocument;\n"
    "         SVGRoot = document.documentElement;\n"
    "         TrueCoords = SVGRoot.createSVGPoint();\n"
    "\n"
    "         toolTip = SVGDocument.getElementById('ToolTip');\n"
    "         tipBox = SVGDocument.getElementById('tipbox');\n"
    "         tipText = SVGDocument.getElementById('tipText');\n"
    "         tipTitle = SVGDocument.getElementById('tipTitle');\n"
    "         tipDesc = SVGDocument.getElementById('tipDesc');\n"
    "      };\n"
    "\n"
    "\n"
    "      function GetTrueCoords(evt)\n"
    "      {\n"
    "         // find the current zoom level and pan setting, and adjust the reported\n"
                "         //    mouse position accordingly\n"
    "         var newScale = SVGRoot.currentScale;\n"
    "         var translation = SVGRoot.currentTranslate;\n"
    "         TrueCoords.x = (evt.clientX - translation.x)/newScale;\n"
    "         TrueCoords.y = (evt.clientY - translation.y)/newScale;\n"
    "      };\n"
    "\n"
    "\n"
    "\n"
    "\n"
    "      function ShowTooltip(evt, turnOn)\n"
    "      {\n"
    "         try\n"
    "         {\n"
    "            if (!evt || !turnOn)\n"
    "            {\n"
    "               toolTip.setAttributeNS(null, 'display', 'none');\n"
    "            }\n"
    "            else\n"
    "            {\n"
    "               var tipScale = 1/SVGRoot.currentScale;\n"
    "               var textWidth = 0;\n"
    "               var tspanWidth = 0;\n"
    "               var boxHeight = 20;\n"
    "\n"
    "               tipBox.setAttributeNS(null, 'transform', 'scale(' + tipScale + ',' + tipScale + ')' );\n"
    "               tipText.setAttributeNS(null, 'transform', 'scale(' + tipScale + ',' + tipScale + ')' );\n"
    "\n"
    "               var targetElement = evt.target;\n"
    "\n"
    "               if ( lastElement != targetElement )\n"
    "               {\n"
    "                  var targetTitle = targetElement.getElementsByTagName('title').item(0);\n"
    "                  if ( targetTitle )\n"
    "                  {\n"
    "                     titleText = targetTitle.firstChild.nodeValue;\n"
    "                     tipTitle.firstChild.nodeValue = titleText;\n"
    "                  }\n"
    "\n"
    "                  var targetDesc = targetElement.getElementsByTagName('desc').item(0);\n"
    "                  if ( targetDesc )\n"
    "                  {\n"
    "                     titleDesc = targetDesc.firstChild.nodeValue;\n"
    "                     tipDesc.firstChild.nodeValue = titleDesc;\n"
    "                  }\n"
    "               }\n"
    "\n"
    "               var xPos = TrueCoords.x + (10 * tipScale);\n"
    "               var yPos = TrueCoords.y + (10 * tipScale);\n"
    "\n"
    "               //return rectangle around object as SVGRect object\n"
    "               var outline = tipText.getBBox();\n"
    "               tipBox.setAttributeNS(null, 'width', Number(outline.width) + 10);\n"
    "               tipBox.setAttributeNS(null, 'height', Number(outline.height) + 10);\n"
    "\n"
    "               toolTip.setAttributeNS(null, 'transform', 'translate(' + xPos + ',' + yPos + ')');\n"
    "               toolTip.setAttributeNS(null, 'display', 'inline');\n"
    "            }\n"
    "         }\n"
    "         catch(er){}\n"
    "       };\n";
