/*
 * Copyright (c) 2009-2016 The University of Tennessee and The University
 *                         of Tennessee Research Foundation.  All rights
 *                         reserved.
 */

#ifndef PARSEC_H_HAS_BEEN_INCLUDED
#define PARSEC_H_HAS_BEEN_INCLUDED

#ifndef PARSEC_BUILDING
#define PARSEC_BUILDING 0
#endif

#ifndef PARSEC_CONFIG_H_HAS_BEEN_INCLUDED
#include "parsec_config.h"
#endif /* #ifndef PARSEC_CONFIG_H */

BEGIN_C_DECLS

/* Define the PaRSEC version */
#define PARSEC_VERSION    2
#define PARSEC_SUBVERSION 0
/* For backward compatibility */
#define PARSEC_VERSION_MAJOR 2
#define PARSEC_VERSION_MINOR 0

#if defined(PARSEC_HAVE_STDDEF_H)
#include <stddef.h>
#endif

typedef struct parsec_handle_s            parsec_handle_t;
typedef struct parsec_execution_context_s parsec_execution_context_t;
typedef struct parsec_execution_unit_s    parsec_execution_unit_t;
/**< The general context that holds all the threads of parsec for this MPI process */
typedef struct parsec_context_s           parsec_context_t;
typedef struct parsec_arena_s             parsec_arena_t;

/**
 * TO BE REMOVED.
 */
typedef void* (*parsec_data_allocate_t)(size_t matrix_size);
typedef void (*parsec_data_free_t)(void *data);
extern parsec_data_allocate_t parsec_data_allocate;
extern parsec_data_free_t     parsec_data_free;

/**
 * CONTEXT MANIPULATION FUNCTIONS.
 */

/**
 * Create a new execution context, using the number of resources passed
 * with the arguments. Every execution happend in the context of such an
 * execution context. Several contextes can cohexist on disjoint resources
 * in same time.
 */
parsec_context_t* parsec_init( int nb_cores, int* pargc, char** pargv[]);

/**
 * Reset the remote_dep comm engine associated with @context, and use
 * the communication context @opaque_comm_ctx in the future
 * (typically an MPI communicator);
 *   parsec_context_wait becomes collective accross nodes spanning on this
 *   communication context.
 */
int parsec_remote_dep_set_ctx( parsec_context_t* context, void* opaque_comm_ctx );


/**
 * Complete all pending operations on the execution context, and release
 * all associated resources. Threads and acclerators attached to this
 * context will be released.
 */
int parsec_fini( parsec_context_t** pcontext );

/**
 * Attach an execution handle on a context, in other words on the set of
 * resources associated to this particular context. A matching between
 * the capabilitis of the context and the support from the handle will be
 * done during this step, which will basically define if accelerators can
 * be used for the execution.
 *
 * @param [INOUT] The parsec context where the tasks generated by the parsec_handle_t
 *                are to be executed.
 * @param [INOUT] The parsec object with pending tasks.
 *
 * @return 0 If the enqueue operation succeeded.
 */
int parsec_enqueue( parsec_context_t* , parsec_handle_t* );

/**
 * Start the runtime by allowing all the other threads to start executing.
 * This call should be paired with one of the completion calls, test or wait.
 *
 * @returns: 0 if the other threads in this context have been started, -1 if the
 * context was already active, -2 if there was nothing to do and no threads hav
 * been activated.
 */
int parsec_context_start(parsec_context_t* context);

/**
 * Check the status of an ongoing execution, started with parsec_start
 *
 * @param [INOUT] The parsec context where the execution is taking place.
 *
 * @return 0 If the execution is still ongoing.
 * @return 1 If the execution is completed, and the parsec_context has no
 *           more pending tasks. All subsequent calls on the same context
 *           will automatically succeed.
 */
int parsec_context_test( parsec_context_t* context );

/**
 * Progress the execution context until no further operations are available.
 * Upon return from this function, all resources (threads and accelerators)
 * associated with the corresponding context are put in a mode where they are
 * not active. New handles enqueued during the progress stage are automatically
 * taken into account, and the caller of this function will not return to the
 * user until all pending handles are completed and all other threads are in a
 * sleeping mode.
 *
 * @param [INOUT] The parsec context where the execution is taking place.
 *
 * @return 0 If the execution is completed.
 * @return * Any other error raised by the tasks themselves.
 */
int parsec_context_wait(parsec_context_t* context);

/**
 * HANDLE MANIPULATION FUNCTIONS.
 */

/**
 * The completion callback of a parsec_handle. Once the handle has been
 * completed, i.e. all the local tasks associated with the handle have
 * been executed, and before the handle is marked as done, this callback
 * will be triggered. Inside the callback the handle should not be
 * modified.
 */
typedef int (*parsec_event_cb_t)(parsec_handle_t* parsec_handle, void*);

/* Accessors to set and get the completion callback and data */
int parsec_set_complete_callback(parsec_handle_t* parsec_handle,
                                parsec_event_cb_t complete_cb, void* complete_data);
int parsec_get_complete_callback(const parsec_handle_t* parsec_handle,
                                parsec_event_cb_t* complete_cb, void** complete_data);
/* Accessors to set and get the enqueue callback and data */
int parsec_set_enqueue_callback(parsec_handle_t* parsec_handle,
                               parsec_event_cb_t enqueue_cb, void* enqueue_data);
int parsec_get_enqueue_callback(const parsec_handle_t* parsec_handle,
                               parsec_event_cb_t* enqueue_cb, void** enqueue_data);

/**< Retrieve the local object attached to a unique object id */
parsec_handle_t* parsec_handle_lookup(uint32_t handle_id);
/**< Reverse an unique ID for the handle. Beware that on a distributed environment the
 * connected objects must have the same ID.
 */
int parsec_handle_reserve_id(parsec_handle_t* handle);
/**< Register the object with the engine. The object must have a unique handle, especially
 * in a distributed environment.
 */
int parsec_handle_register(parsec_handle_t* handle);
/**< Unregister the object with the engine. This make the handle available for
 * future handles. Beware that in a distributed environment the connected objects
 * must have the same ID.
 */
void parsec_handle_unregister(parsec_handle_t* handle);
/**< globally synchronize object id's so that next register generates the same
 *  id at all ranks. */
void parsec_handle_sync_ids(void);

/**
 * Sequentially compose two handles, triggering the start of next upon
 * completion of start. If start is already a composed object, then next will be
 * appended to the already existing list. These handles will execute one after
 * another as if there were sequential.  The resulting compound parsec_handle is
 * returned.
 */
parsec_handle_t* parsec_compose(parsec_handle_t* start, parsec_handle_t* next);

/**< Free the resource allocated in the parsec handle. The handle should be unregistered first. */
void parsec_handle_free(parsec_handle_t *handle);

/**
 * The final step of a handle activation. At this point we assume that all the local
 * initializations have been successfully completed for all components, and that the
 * handle is ready to be registered with the system, and any potential pending tasks
 * ready to go. If distributed is non 0, then the runtime assumes that the handle has
 * a distributed scope and should be registered with the communication engine.
 *
 * The local_task allows for concurrent management of the startup_queue, and provide a way
 * to prevent a task from being added to the scheduler. As the different tasks classes are
 * initialized concurrently, we need a way to prevent the beginning of the tasks generation until
 * all the tasks classes associated with a DAG are completed. Thus, until the synchronization
 * is complete, the task generators are put on hold in the startup_queue. Once the handle is
 * ready to advance, and this is the same moment as when the handle is ready to be enabled,
 * we reactivate all pending tasks, starting the tasks generation step for all type classes.
 */
int parsec_handle_enable(parsec_handle_t* handle,
                        parsec_execution_context_t** startup_queue,
                        parsec_execution_context_t* local_task,
                        parsec_execution_unit_t * eu,
                        int nb_tasks);

/**< Print PaRSEC usage message */
void parsec_usage(void);

/**
 * Allow to change the default priority of an object. It returns the
 * old priority (the default priorityy of an object is 0). This function
 * can be used during the lifetime of an object, however, only tasks
 * generated after this call will be impacted.
 */
int32_t parsec_set_priority( parsec_handle_t* object, int32_t new_priority );

/* Dump functions */
char* parsec_snprintf_execution_context( char* str, size_t size,
                                        const parsec_execution_context_t* task);
struct parsec_function_s;
struct assignment_s;
char* parsec_snprintf_assignments( char* str, size_t size,
                                  const struct parsec_function_s* function,
                                  const struct assignment_s* locals);

END_C_DECLS

#endif  /* PARSEC_H_HAS_BEEN_INCLUDED */
