if(PARSEC_HAVE_CUDA)
  parsec_addtest_cmd(dsl/ptg/cuda/get_best_device:gpu ${SHM_TEST_CMD_LIST} ${CTEST_CUDA_LAUNCHER_OPTIONS} dsl/ptg/cuda/testing_get_best_device -N 400 -t 20 -g 1)
  if(TARGET nvlink)
    parsec_addtest_cmd(dsl/ptg/cuda/nvlink:gpu ${SHM_TEST_CMD_LIST} ${CTEST_CUDA_LAUNCHER_OPTIONS} dsl/ptg/cuda/nvlink --mca device_cuda_enable 2)
  endif()
  if(TARGET stress)
    parsec_addtest_cmd(dsl/ptg/cuda/stress:gpu ${SHM_TEST_CMD_LIST} ${CTEST_CUDA_LAUNCHER_OPTIONS} dsl/ptg/cuda/stress)
  endif()
  if(TARGET stage)
    parsec_addtest_cmd(dsl/ptg/cuda/stage:gpu ${SHM_TEST_CMD_LIST} ${CTEST_CUDA_LAUNCHER_OPTIONS} dsl/ptg/cuda/stage)
  endif()
endif()
