#include "dague_config.h"
#include "pins.h"
#include "dague/mca/pins/papi_exec/pins_papi_exec.h"
#include "dague/mca/pins/papi_socket/pins_papi_socket.h"
#include "dague/mca/pins/papi_select/pins_papi_select.h"
#include "execution_unit.h"
#include "profiling.h"

/*
 These should really be generated by the build process,
 but for now they can be built by hand. --PETER
 */

void empty_callback(dague_execution_unit_t * exec_unit, dague_execution_context_t * task, void * data);

extern parsec_pins_callback * pins_array[];

void pins_init(dague_context_t * master_context) {
  int i = 0;
  for (; i < PINS_FLAG_COUNT; i++) {
    if (pins_array[i] == NULL)
      pins_array[i] = &empty_callback;
  }
  DEBUG(("Initialized PaRSEC PINS callbacks to empty_callback()"));

#ifdef PINS_PAPI_EXEC	
	pins_init_papi_exec(master_context);
#endif // PINS_PAPI_EXEC

#ifdef PINS_PAPI_SELECT
	pins_init_papi_select(master_context);
#endif // PINS_PAPI_SELECT

#ifdef PINS_PAPI_SOCKET
	pins_init_papi_socket(master_context);
#endif

}

void pins_thread_init(dague_execution_unit_t * exec_unit) {

#ifdef PINS_PAPI_EXEC	
	pins_thread_init_papi_exec(exec_unit);
#endif // PINS_PAPI_EXEC

#ifdef PINS_PAPI_SELECT
	pins_thread_init_papi_select(exec_unit);
#endif // PINS_PAPI_SELECT

	parsec_pins(THREAD_INIT, exec_unit, NULL, NULL);
}

void pins_thread_fini(dague_execution_unit_t * exec_unit) {

	parsec_pins(THREAD_FINI, exec_unit, NULL, NULL);
}


void pins_handle_init(dague_handle_t * handle) {

#ifdef PINS_PAPI_EXEC	
	pins_handle_init_papi_exec(handle);
#endif // PINS_PAPI_EXEC

	parsec_pins(HANDLE_INIT, NULL, NULL, (void *)handle);
}

void pins_handle_fini(dague_handle_t * handle) {
	/*
#ifdef PINS_PAPI_SELECT
	pins_handle_fini_papi_select(handle);
#endif // PINS_PAPI_SELECT
	 */

	parsec_pins(HANDLE_FINI, NULL, NULL, (void *)handle);
}
