#!/usr/bin/php -q
<?php
echo "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n";

$ALLXML = array();
$totaltime = 0;
for( $fileidx = 1; $fileidx < $argc; $fileidx++ ) {
    
    $xml = simplexml_load_file( $argv[$fileidx] );
    if( !$xml ) {
        echo "<!-- Parse Error in $argv[$fileidx] -->\n";
        continue;
    }
    if( $xml->PROFILES['TOTAL_DURATION'] > $totaltime )
        $totaltime = $xml->PROFILES['TOTAL_DURATION'];
    $xml->FILENAME=$argv[$fileidx];
    $ALLXML[] = $xml;
 }

echo "<PROFILING>\n";

if( count($ALLXML) == 0 ) {
    echo "</PROFILING>\n";
    exit;
}
$REFXML = $ALLXML[0];
echo "  <IDENTIFIER><![CDATA[" . $REFXML->IDENTIFIER . "]]></IDENTIFIER>\n";
echo $REFXML->INFOS->asXML();
echo $REFXML->DICTIONARY->asXML();
echo "  <DISTRIBUTED_PROFILE TOTAL_DURATION=\"$totaltime\" TIME_UNIT=\"" . $REFXML->PROFILES['TIME_UNIT']  . "\">\n";

foreach($ALLXML as $xml) {
    echo "    <NODE FILEID=\"" . $xml->FILENAME . "\">\n";
    echo $xml->PROFILES->asXML();
    echo "    </NODE>\n";
}

echo "</DISTRIBUTED_PROFILE>\n";
echo "</PROFILING>\n";
?>
