#!/usr/bin/php -q
<?php

$proc = 0;
$XML = array();
$keys = null;

for($fileidx = 1; $fileidx < $argc; $fileidx++ ) {
    $xml = simplexml_load_file( $argv[$fileidx] );
    if( !$xml ) {
        error_log("Parse Error in $argv[$fileidx]\n");
        continue;
    }

    if( $proc == 0 ) {
        $keys = $xml->DICTIONARY;
    } else {
        $nk = $xml->DICTIONARY;
        $kid = 0;
        foreach( $keys->KEY as $k ) {
            $n1 = $k->NAME;
            $n2 = $nk->KEY[$kid]->NAME;
            if( "$n1" != "$n2" ) {
                error_log("$n1 != $n2 -> Dictionaries don't match. All dictionaries must match\n");
                exit;
            } 
            $kid++;
        }
    }

    $XML[] = $xml;
    $proc++;
}

echo "#proc\tthid\tkey\teventid\tstart\tend\tduration\n";
$tu = $XML[0]->PROFILES['TIME_UNIT'];
echo "#time units: $tu\n";

$proc = 0;
foreach($XML as $xml) {
    $thid = 0;
    foreach( $xml->PROFILES->THREAD as $th ) {
        foreach( $th->KEY as $key ) {
            $nb = $key['ID'];
            $kn = "NOTFOUND";
            foreach($keys->KEY as $k) {
                if( $k['ID'] == "$nb" ) {
                    $kn = $k->NAME;
                    break;
                }
            }
            foreach( $key->EVENT as $e ) {
                $start = $e->START;
                $end = $e->END;
                $id = $e->ID;
                $duration = $end-$start;
                echo "$proc\t$thid\t$kn\t$id\t$start\t$end\t$duration\n";
            }
        }
        $thid++;
    }
    $proc++;
}

?>