set(alltreel 0 1 2 3 )
set(alltreeh 0 1 2 3 )
set(allP 3 5 7 8)
set(allA 1 2 4 7)
#set(allM 1 2 3 4 5 10 13 17 25 26 58 128)
#set(allN 1 2 3 4 5 10 13 17 25 26 58 128)
set(allM 1 3 4 10 17 25 128)
set(allN 1 2 5 13 26 58)

foreach( treel ${alltreel} )
  foreach( a ${allA} )
    foreach( m ${allM} )
      foreach( n ${allN} )
        add_test(pivgen_l${treel}_a${a}_m${m}_n${n} ./testing_dpivgen -M ${m} -N ${n} --treel=${treel} --qr_a=${a} --qr_p=1 )
        add_test(qrparam_l${treel}_a${a}_m${m}_n${n} ./testing_dgeqrf_param -t 1 -i 1 -M ${m} -N ${n} --treel=${treel} --qr_a=${a} --qr_p=1 )
      endforeach()
    endforeach()
  endforeach()

  foreach( domino 0 1 )
    foreach( treeh ${alltreeh} )
      foreach( p ${allP} )
        foreach( a ${allA} )
          foreach( m ${allM} )
            foreach( n ${allN} )
              add_test(pivgen_h${treeh}_p${p}_d${domino}_l${treel}_a${a}_m${m}_n${n} ./testing_dpivgen -M ${m} -N ${n} --treel=${treel} --qr_a=${a} --qr_p=${p} --treeh=${treeh} --domino=${domino})
              add_test(qrparam_h${treeh}_p${p}_d${domino}_l${treel}_a${a}_m${m}_n${n} ./testing_dgeqrf_param -t 1 -i 1 -M ${m} -N ${n} --treel=${treel} --qr_a=${a} --qr_p=${p} --treeh=${treeh} --domino=${domino})
            endforeach()
          endforeach()
        endforeach()
      endforeach()
    endforeach()
  endforeach()
endforeach()