#!/bin/sh

mpirun --mca btl_tcp_if_include eth0,eth1 -np 8 -hostfile ~lemarini/hostfile --bynode  $HOME/dplasma/tests/cholesky/mpi_dposv_rl -c 4 -B $1 4000 -g 4 2>&1 | tee /dev/stderr | awk '$11 == "GFLOPS" {print $10}'
