#!/usr/bin/env python

# this is a PURE PYTHON interface to
# pure Python objects generated by py_dbpreader.

# It is especially suitable for use when a separate
# Python program has done the reading of the profile
# and stored the profile in this format in some sort
# of cross-process format, such as a pickle.

import sys, os
import pandas as pd
        
class ParsecProfile(object): 
    class_version = 1.0 # created 2013.10.22 after move to pandas
    basic_event_columns = ['filerank', 'thread', 'key', 'flags', 'handle_id',
                           'id', 'begin', 'end', 'duration', 'unique_id']
    HDF_ATTR_NAMES = ['event_types', 'type_names', 'files', 'errors'] 
    @staticmethod
    def from_hdf(filename):
        store = pd.HDFStore(filename, 'r')
        profile = ParsecProfile(store['events'],
                                store['event_types'],
                                store['type_names'],
                                store['files'],
                                store['errors'])
        profile.store = profile.to_hdf
        profile.store_name = filename
        store.close()
        return profile
    @staticmethod
    def from_native(filenames, translate=True):
        import py_dbpreader
        profile = py_dbpreader.readProfile(filenames)
        profile.store_name = filenames[0] # fix later
        if translate:
            filename = filenames[0].replace('.prof-', '.h5-')
            store = profile.to_hdf(filename)
            profile.store = profile.to_hdf
            profile.store_name = filename
            store.close()
            for filename in filenames:
                os.remove(filename)
        return profile
        
    # the init function should not ordinarily be used
    # it is better to use from_hdf(), from_native(), or autoload()
    def __init__(self, events, event_types, type_names, files, errors):
        self.__version__ = self.__class__.class_version
        self.events = events
        self.event_types = event_types
        self.type_names = type_names
        self.files = files
        self.errors = errors
        self.basic_columns = ParsecProfile.basic_event_columns
        self.store = None
        self.store_name = None
    def to_hdf(self, filename, table=False, append=False):
        store = pd.HDFStore(filename)
        for name in ParsecProfile.HDF_ATTR_NAMES:
            store.put(name, self.__dict__[name])
        store.put('events', self.events, table=table, append=append)
        return store
        
        
