#!/usr/bin/env python3
"""
One-shot script for building PaRSEC and installing the Python bindings.

This script lives at python/build_parsec4python.py inside the PaRSEC
source tree.  It:
  - creates a venv (optional)
  - installs Python deps (+ mpi4py)
  - builds/installs PaRSEC via CMake into ../build/install
  - generates parsec_env.sh
  - pip-installs py-parsec (editable by default)
"""

import argparse
import os
import sys
import subprocess
import shutil
from pathlib import Path


def run(cmd, cwd=None, env=None, shell=False, check=True):
    if shell:
        print(f"Running: {cmd}")
    else:
        print("Running:", " ".join(map(str, cmd)))
    return subprocess.run(cmd, cwd=cwd, env=env, shell=shell, check=check, text=True)


def which_exists(x):
    return shutil.which(x) is not None


def ensure_utf8_env(base_env=None):
    env = dict(base_env or os.environ)
    env.setdefault("LANG", "C.UTF-8")
    env.setdefault("LC_ALL", "C.UTF-8")
    env.setdefault("PYTHONUTF8", "1")
    env.setdefault("PYTHONIOENCODING", "utf-8")
    return env


def venv_paths(python_root: Path):
    venv = python_root / "venv"
    if sys.platform.startswith("win"):
        py = venv / "Scripts" / "python"
        pip = venv / "Scripts" / "pip"
    else:
        py = venv / "bin" / "python"
        pip = venv / "bin" / "pip"
    return venv, py, pip


def create_or_reuse_venv(python_root: Path):
    venv, vpy, vpip = venv_paths(python_root)
    if not venv.exists():
        run([sys.executable, "-m", "venv", str(venv)])
    return venv, vpy, vpip


def install_python_deps(vpy: Path, requirements: Path):
    run([str(vpy), "-m", "pip", "install", "--upgrade", "pip", "setuptools", "wheel", "build"])
    if requirements.exists():
        run([str(vpy), "-m", "pip", "install", "-r", str(requirements)])
    run([str(vpy), "-m", "pip", "install", "mpi4py", "Cython", "numpy"])


def build_parsec(parsec_repo_root: Path, enable_cuda=False, enable_hip=False,
                 enable_opencl=False, cuda_home=None):
    """Build PaRSEC from the parent repo root via CMake."""
    build_dir = parsec_repo_root / "build"
    install_prefix = build_dir / "install"
    build_dir.mkdir(exist_ok=True)

    cmake = shutil.which("cmake")
    if not cmake:
        raise RuntimeError("cmake not found in PATH")

    cmake_cmd = [
        cmake, str(parsec_repo_root),
        f"-DCMAKE_INSTALL_PREFIX={install_prefix}",
        "-DCMAKE_BUILD_TYPE=Release",
        f"-DPARSEC_GPU_WITH_CUDA={'ON' if enable_cuda else 'OFF'}",
        f"-DPARSEC_GPU_WITH_HIP={'ON' if enable_hip else 'OFF'}",
        f"-DPARSEC_GPU_WITH_OPENCL={'ON' if enable_opencl else 'OFF'}",
    ]
    if enable_cuda and cuda_home:
        cmake_cmd.append(f"-DCUDAToolkit_ROOT={cuda_home}")
    run(cmake_cmd, cwd=build_dir)
    run(["cmake", "--build", ".", "-j", str(os.cpu_count() or 8)], cwd=build_dir)
    run(["cmake", "--install", "."], cwd=build_dir)

    header = install_prefix / "include" / "parsec.h"
    if not header.exists():
        raise RuntimeError(f"PaRSEC built but parsec.h not found at {header}")
    return install_prefix


def find_mpi_wrappers():
    mpicc = shutil.which("mpicc")
    mpicxx = shutil.which("mpicxx") or shutil.which("mpiCC")
    return mpicc, mpicxx


def find_cuda_home():
    for k in ("CUDA_HOME", "CUDA_PATH", "CUDA_ROOT"):
        v = os.environ.get(k)
        if v:
            p = Path(v)
            if (p / "include" / "cuda.h").exists():
                return p

    nvcc = shutil.which("nvcc")
    if not nvcc:
        return None
    nvcc_p = Path(os.path.realpath(nvcc))
    cuda_home = nvcc_p.parent.parent
    if (cuda_home / "include" / "cuda.h").exists():
        return cuda_home
    return None


def prepend_env(env: dict, key: str, value: str, sep: str = ":"):
    if not value:
        return
    old = env.get(key, "")
    env[key] = value if not old else f"{value}{sep}{old}"


def add_cuda_to_build_env(env: dict):
    cuda_home = find_cuda_home()
    if not cuda_home:
        return env

    env["CUDA_HOME"] = str(cuda_home)

    inc = str(cuda_home / "include")
    prepend_env(env, "CPATH", inc, sep=":")
    prepend_env(env, "CFLAGS", f"-I{inc}", sep=" ")
    prepend_env(env, "CPPFLAGS", f"-I{inc}", sep=" ")

    if (cuda_home / "lib64").exists():
        lib = str(cuda_home / "lib64")
    elif (cuda_home / "lib").exists():
        lib = str(cuda_home / "lib")
    else:
        lib = None

    if lib:
        prepend_env(env, "LIBRARY_PATH", lib, sep=":")
        prepend_env(env, "LD_LIBRARY_PATH", lib, sep=":")

    return env


def write_parsec_env_sh(python_root: Path, parsec_root: Path):
    sh = python_root / "parsec_env.sh"
    libdir = "lib64" if (parsec_root / "lib64").exists() else "lib"

    content = f"""#!/usr/bin/env bash
# Auto-generated by build_parsec4python.py
ROOT="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"

export PARSEC_ROOT="{parsec_root}"
export CPATH="$PARSEC_ROOT/include${{CPATH:+:$CPATH}}"
export LIBRARY_PATH="$PARSEC_ROOT/{libdir}${{LIBRARY_PATH:+:$LIBRARY_PATH}}"
export LD_LIBRARY_PATH="$PARSEC_ROOT/{libdir}${{LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}}"

# Prefer MPI wrappers if available
command -v mpicc >/dev/null 2>&1 && export CC="${{CC:-mpicc}}"
command -v mpicxx >/dev/null 2>&1 && export CXX="${{CXX:-mpicxx}}"

# --- CUDA (optional) ---
if [ -z "${{CUDA_HOME:-}}" ]; then
  _nvcc_path="$(command -v nvcc 2>/dev/null || true)"
  if [ -n "$_nvcc_path" ]; then
    CUDA_HOME="$(dirname "$(dirname "$(readlink -f "$_nvcc_path")")")"
    export CUDA_HOME
  fi
fi

if [ -n "${{CUDA_HOME:-}}" ] && [ -f "$CUDA_HOME/include/cuda.h" ]; then
  export CPATH="$CUDA_HOME/include${{CPATH:+:$CPATH}}"
  export CFLAGS="-I$CUDA_HOME/include ${{CFLAGS:-}}"
  export CPPFLAGS="-I$CUDA_HOME/include ${{CPPFLAGS:-}}"
  if [ -d "$CUDA_HOME/lib64" ]; then
    export LIBRARY_PATH="$CUDA_HOME/lib64${{LIBRARY_PATH:+:$LIBRARY_PATH}}"
    export LD_LIBRARY_PATH="$CUDA_HOME/lib64${{LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}}"
  elif [ -d "$CUDA_HOME/lib" ]; then
    export LIBRARY_PATH="$CUDA_HOME/lib${{LIBRARY_PATH:+:$LIBRARY_PATH}}"
    export LD_LIBRARY_PATH="$CUDA_HOME/lib${{LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}}"
  fi
fi

echo "[parsec_env] PARSEC_ROOT=$PARSEC_ROOT"
[ -n "${{CUDA_HOME:-}}" ] && echo "[parsec_env] CUDA_HOME=$CUDA_HOME"
"""
    sh.write_text(content)
    sh.chmod(0o755)


def pip_install_package(vpy: Path, python_root: Path, parsec_root: Path,
                        editable=True, verbose=True):
    env = ensure_utf8_env()

    libdir = "lib64" if (parsec_root / "lib64").exists() else "lib"
    env["PARSEC_ROOT"] = str(parsec_root)

    prepend_env(env, "CPATH", f"{parsec_root}/include", sep=":")
    prepend_env(env, "LIBRARY_PATH", f"{parsec_root}/{libdir}", sep=":")
    prepend_env(env, "LD_LIBRARY_PATH", f"{parsec_root}/{libdir}", sep=":")

    mpicc, mpicxx = find_mpi_wrappers()
    if mpicc:
        env["CC"] = mpicc
    if mpicxx:
        env["CXX"] = mpicxx

    env = add_cuda_to_build_env(env)

    cmd = [str(vpy), "-m", "pip", "install"]
    if editable:
        cmd += ["-e"]
    cmd += [".", "--no-build-isolation"]
    if verbose:
        cmd += ["-v"]

    build_dir = python_root / "build"
    if build_dir.exists():
        shutil.rmtree(build_dir)
    dtd_c = python_root / "src" / "py_parsec" / "dtd.c"
    if dtd_c.exists():
        dtd_c.unlink()
    py_parsec_dir = python_root / "src" / "py_parsec"
    for nfs_file in py_parsec_dir.glob(".nfs*"):
        try:
            nfs_file.unlink()
        except OSError:
            pass

    def pip_supports_no_use_pep517():
        try:
            help_out = subprocess.run(
                [str(vpy), "-m", "pip", "install", "--help"],
                capture_output=True, text=True,
            )
            return "--no-use-pep517" in (help_out.stdout or "") or "--no-use-pep517" in (help_out.stderr or "")
        except Exception:
            return False

    if editable and pip_supports_no_use_pep517():
        legacy_cmd = cmd + ["--no-use-pep517"]
        try:
            run(legacy_cmd, cwd=python_root, env=env)
            return
        except subprocess.CalledProcessError:
            pass

    run(cmd, cwd=python_root, env=env)


def main():
    ap = argparse.ArgumentParser(
        description="Build PaRSEC and install the Python bindings (py-parsec)."
    )
    ap.add_argument("--version", default="main",
                    help="PaRSEC branch/tag to checkout in parent repo (default: main)")
    ap.add_argument("--enable-cuda", action="store_true")
    ap.add_argument("--enable-hip", action="store_true")
    ap.add_argument("--enable-opencl", action="store_true")
    ap.add_argument("--skip-env", action="store_true",
                    help="skip creating venv and installing python deps")
    ap.add_argument("--skip-parsec", action="store_true",
                    help="skip building PaRSEC (assume ../build/install exists)")
    ap.add_argument("--non-editable", action="store_true",
                    help="install py-parsec non-editable")
    args = ap.parse_args()

    python_root = Path(__file__).resolve().parent
    parsec_repo_root = python_root.parent
    requirements = python_root / "requirements.txt"

    for x in ["cmake"]:
        if not which_exists(x):
            raise RuntimeError(f"{x} not found in PATH")

    # venv + python deps
    venv, vpy, _ = venv_paths(python_root)
    if not args.skip_env:
        venv, vpy, _ = create_or_reuse_venv(python_root)
        install_python_deps(vpy, requirements)
    else:
        if not vpy.exists():
            raise RuntimeError(
                "skip-env set but venv/python not found. "
                "Create venv first or don't use --skip-env."
            )

    # Optionally checkout a specific PaRSEC version in the parent repo
    if args.version and args.version != "main":
        run(["git", "checkout", args.version], cwd=parsec_repo_root)

    # PaRSEC build/install
    parsec_install = parsec_repo_root / "build" / "install"
    if not args.skip_parsec:
        cuda_home = find_cuda_home()
        enable_cuda = args.enable_cuda or (cuda_home is not None)
        if args.enable_cuda and cuda_home is None:
            print("WARNING: --enable-cuda set but nvcc/cuda.h not found; building without CUDA")
            enable_cuda = False
        elif (not args.enable_cuda) and enable_cuda:
            print(f"Auto-enabled CUDA using {cuda_home}")
        parsec_install = build_parsec(
            parsec_repo_root, enable_cuda, args.enable_hip, args.enable_opencl,
            cuda_home=cuda_home,
        )
    else:
        hdr = parsec_install / "include" / "parsec.h"
        if not hdr.exists():
            raise RuntimeError(f"--skip-parsec used but {hdr} not found")

    write_parsec_env_sh(python_root, parsec_install)

    pip_install_package(
        vpy, python_root, parsec_install,
        editable=(not args.non_editable), verbose=True,
    )

    print("\n✅ All done.")
    print("New terminal usage:")
    print("  source python/venv/bin/activate")
    print("  source python/parsec_env.sh")
    print('  python -c "import py_parsec; print(\'ok\')"')


if __name__ == "__main__":
    main()
