#include "pins.h"
#include "steals/steals.h"
#include "papi/cachemiss.h"
#include "execution_unit.h"

/*
 These should really be generated by the build process,
 but for now they can be built by hand. --PETER
 */

void empty_callback(dague_execution_unit_t * exec_unit, dague_execution_context_t * task, void * data);

extern parsec_pins_callback * pins_array[];

void pins_init(dague_context_t * master_context) {
  int i = 0;
  for (; i < A_COUNT_NOT_A_FLAG; i++) {
    if (pins_array[i] == NULL)
      pins_array[i] = &empty_callback;
  }
  DEBUG(("Initialized PaRSEC PINS callbacks to empty_callback()"));

#ifdef PINS_EXEC_MISSES	
	pins_init_cachemiss(master_context);
#endif // PINS_EXEC_MISSES
#ifdef PINS_SCHED_STEALS
	pins_init_steals(master_context);
#endif // PINS_SCHED_STEALS
}

void pins_thread_init(dague_execution_unit_t * exec_unit) {
#ifdef PINS_ENABLE
#ifdef PINS_EXEC_MISSES	
	pins_thread_init_cachemiss(exec_unit);
#endif // PINS_EXEC_MISSES
#ifdef PINS_SCHED_STEALS
	pins_thread_init_steals(exec_unit);
#endif // PINS_SCHED_STEALS
#endif	
}


void pins_handle_init(dague_handle_t * handle) {
#ifdef PINS_ENABLE
	// create the per-exec_unit array
	struct dague_context_s * context = handle->context;
	int num_cores = 0;
	int i = 0;
	for (i = 0; i < context->nb_vp; i++)
		num_cores += context->virtual_processes[i]->nb_cores;

	handle->pins_data = (unsigned int **) calloc(sizeof(int *), num_cores);
	for (i = 0; i < num_cores; i++)
		handle->pins_data[i] = (void **) calloc(sizeof(void *), A_COUNT_NOT_A_FLAG);
#ifdef PINS_EXEC_MISSES	
	pins_handle_init_cachemiss(handle);
#endif // PINS_EXEC_MISSES
#ifdef PINS_SCHED_STEALS
	pins_handle_init_steals(handle);
#endif // PINS_SCHED_STEALS
#endif // PINS_ENABLE
}
