# Copyright (c) 2026 NVIDIA Corporation.  All rights reserved.

#
# Shared Memory Testings
#
parsec_addtest_cmd(dsl/dtd/empty ${SHM_TEST_CMD_LIST} dsl/dtd/dtd_test_empty)
parsec_addtest_cmd(dsl/dtd/task_generation ${SHM_TEST_CMD_LIST} dsl/dtd/dtd_test_task_generation)
parsec_addtest_cmd(dsl/dtd/task_inserting_task ${SHM_TEST_CMD_LIST} dsl/dtd/dtd_test_task_inserting_task)
parsec_addtest_cmd(dsl/dtd/task_insertion ${SHM_TEST_CMD_LIST} dsl/dtd/dtd_test_task_insertion)
parsec_addtest_cmd(dsl/dtd/war ${SHM_TEST_CMD_LIST} dsl/dtd/dtd_test_war)
parsec_addtest_cmd(dsl/dtd/interleave_actions ${SHM_TEST_CMD_LIST} dsl/dtd/dtd_test_interleave_actions)
parsec_addtest_cmd(dsl/dtd/allreduce ${SHM_TEST_CMD_LIST} dsl/dtd/dtd_test_allreduce)
parsec_addtest_cmd(dsl/dtd/broadcast ${SHM_TEST_CMD_LIST} dsl/dtd/dtd_test_broadcast)
parsec_addtest_cmd(dsl/dtd/data_flush ${SHM_TEST_CMD_LIST} dsl/dtd/dtd_test_data_flush)
parsec_addtest_cmd(dsl/dtd/global_id_for_dc_assumed ${SHM_TEST_CMD_LIST} dsl/dtd/dtd_test_global_id_for_dc_assumed)
parsec_addtest_cmd(dsl/dtd/hierarchy ${SHM_TEST_CMD_LIST} dsl/dtd/dtd_test_hierarchy)
parsec_addtest_cmd(dsl/dtd/insert_task_interface ${SHM_TEST_CMD_LIST} dsl/dtd/dtd_test_insert_task_interface)
parsec_addtest_cmd(dsl/dtd/flag_dont_track ${SHM_TEST_CMD_LIST} dsl/dtd/dtd_test_flag_dont_track)
parsec_addtest_cmd(dsl/dtd/multiple_handle_wait ${SHM_TEST_CMD_LIST} dsl/dtd/dtd_test_multiple_handle_wait)
parsec_addtest_cmd(dsl/dtd/null_as_tile ${SHM_TEST_CMD_LIST} dsl/dtd/dtd_test_null_as_tile)
parsec_addtest_cmd(dsl/dtd/reduce ${SHM_TEST_CMD_LIST} dsl/dtd/dtd_test_reduce)
parsec_addtest_cmd(dsl/dtd/explicit_task_creation ${SHM_TEST_CMD_LIST} dsl/dtd/dtd_test_explicit_task_creation)
parsec_addtest_cmd(dsl/dtd/template_counter ${SHM_TEST_CMD_LIST} dsl/dtd/dtd_test_template_counter)
parsec_addtest_cmd(dsl/dtd/untie ${SHM_TEST_CMD_LIST} dsl/dtd/dtd_test_untie)
parsec_addtest_cmd(dsl/dtd/new_tile:cpu ${SHM_TEST_CMD_LIST} dsl/dtd/dtd_test_new_tile --mca device_cuda_enabled 0)
if(PARSEC_HAVE_CUDA AND CMAKE_CUDA_COMPILER)
  parsec_addtest_cmd(dsl/dtd/new_tile:gpu ${SHM_TEST_CMD_LIST} ${CTEST_CUDA_LAUNCHER_OPTIONS} dsl/dtd/dtd_test_new_tile --mca device_cuda_enabled 1 --mca device cuda)
endif(PARSEC_HAVE_CUDA AND CMAKE_CUDA_COMPILER)
if(PARSEC_HAVE_DEV_CAPABILITY_BATCH)
  parsec_addtest_cmd(dsl/dtd/batch_cpu ${SHM_TEST_CMD_LIST} dsl/dtd/dtd_test_batch_cpu)
  parsec_addtest_cmd(dsl/dtd/batch_cpu:disabled ${SHM_TEST_CMD_LIST} dsl/dtd/dtd_test_batch_cpu --mca device_enable_batching 0)
endif(PARSEC_HAVE_DEV_CAPABILITY_BATCH)

#
# Distributed Memory Testings
#
if( MPI_C_FOUND )
  parsec_addtest_cmd(dsl/dtd/empty:mp ${MPI_TEST_CMD_LIST} 2 dsl/dtd/dtd_test_empty)
  parsec_addtest_cmd(dsl/dtd/pingpong:mp ${MPI_TEST_CMD_LIST} 2 dsl/dtd/dtd_test_pingpong)
  parsec_addtest_cmd(dsl/dtd/task_inserting_task:mp ${MPI_TEST_CMD_LIST} 4 dsl/dtd/dtd_test_task_inserting_task)
  parsec_addtest_cmd(dsl/dtd/task_insertion:mp ${MPI_TEST_CMD_LIST} 4 dsl/dtd/dtd_test_task_insertion)
  parsec_addtest_cmd(dsl/dtd/war:mp ${MPI_TEST_CMD_LIST} 4 dsl/dtd/dtd_test_war)
  parsec_addtest_cmd(dsl/dtd/interleave_actions:mp ${MPI_TEST_CMD_LIST} 4 dsl/dtd/dtd_test_interleave_actions)
  parsec_addtest_cmd(dsl/dtd/allreduce:mp ${MPI_TEST_CMD_LIST} 4 dsl/dtd/dtd_test_allreduce)
  parsec_addtest_cmd(dsl/dtd/broadcast:mp ${MPI_TEST_CMD_LIST} 4 dsl/dtd/dtd_test_broadcast)
  parsec_addtest_cmd(dsl/dtd/data_flush:mp:2 ${MPI_TEST_CMD_LIST} 2 dsl/dtd/dtd_test_data_flush)
  parsec_addtest_cmd(dsl/dtd/data_flush:mp:3 ${MPI_TEST_CMD_LIST} 3 dsl/dtd/dtd_test_data_flush)
  parsec_addtest_cmd(dsl/dtd/global_id_for_dc_assumed:mp ${MPI_TEST_CMD_LIST} 2 dsl/dtd/dtd_test_global_id_for_dc_assumed)
  parsec_addtest_cmd(dsl/dtd/hierarchy:mp ${MPI_TEST_CMD_LIST} 2 dsl/dtd/dtd_test_hierarchy)
  parsec_addtest_cmd(dsl/dtd/multiple_handle_wait:mp ${MPI_TEST_CMD_LIST} 2 dsl/dtd/dtd_test_multiple_handle_wait)
  parsec_addtest_cmd(dsl/dtd/null_as_tile:mp ${MPI_TEST_CMD_LIST} 2 dsl/dtd/dtd_test_null_as_tile)
  parsec_addtest_cmd(dsl/dtd/reduce:mp ${MPI_TEST_CMD_LIST} 4 dsl/dtd/dtd_test_reduce)
  parsec_addtest_cmd(dsl/dtd/task_placement:mp ${MPI_TEST_CMD_LIST} 2 dsl/dtd/dtd_test_task_placement)
  parsec_addtest_cmd(dsl/dtd/template_counter:mp ${MPI_TEST_CMD_LIST} 2 dsl/dtd/dtd_test_template_counter)
  parsec_addtest_cmd(dsl/dtd/new_tile:mp:cpu ${MPI_TEST_CMD_LIST} 2 dsl/dtd/dtd_test_new_tile --mca device_cuda_enabled 0)
  if(PARSEC_HAVE_CUDA AND CMAKE_CUDA_COMPILER)
    parsec_addtest_cmd(dsl/dtd/new_tile:mp:gpu ${MPI_TEST_CMD_LIST} 2 ${CTEST_CUDA_LAUNCHER_OPTIONS} dsl/dtd/dtd_test_new_tile --mca device_cuda_enabled 1 --mca device cuda)
  endif(PARSEC_HAVE_CUDA AND CMAKE_CUDA_COMPILER)
endif( MPI_C_FOUND )
